// Generated by IcedCoffeeScript 1.6.3-f
(function() {
  var browser_rng, e, rng, _ref;



  browser_rng = function(n) {
    var v;
    v = new Uint8Array(n);
    window.crypto.getRandomValues(v);
    return new Buffer(v);
  };

  if ((typeof window !== "undefined" && window !== null ? (_ref = window.crypto) != null ? _ref.getRandomValues : void 0 : void 0) != null) {
    exports.rng = browser_rng;
  } else {
    try {
      rng = require('crypto').rng;
      if (rng != null) {
        exports.rng = rng;
      }
    } catch (_error) {
      e = _error;
    }
  }

  if (exports.rng == null) {
    throw new Error('No rng found; tried requiring "crypto" and window.crypto');
  }

}).call(this);
